collections:
  projects:
    output: true
    permalink: /:collection/:name
    order:
      - 2021-virtual-tour.md
      - 2019-wedding.md
      - IntSoc.md
      - Bla-Bla-language-Cafe.md
      - Glastonbury_Close_Circle_Proposal.md
      - 16th_Bday_Party_Proposal.md
  testimonials:
  jobs:
    order:
      - project_management/attached.md
      - project_management/transperfect.md
      - project_management/gist.md
      - customer_service/booking.md
      - customer_service/plantage.md
      - customer_service/gist.md
      - comms_marketing/do_teacher_training.md
      - comms_marketing/newcastle.md
      - comms_marketing/together_abroad.md

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
