baseurl: "/"

collections:
  events:
    output: true
    permalink: /:collection/:name

  proposals:
    output: true
    permalink: /:collection/:name

  testimonials:

  jobs:

  hobbies:

  summaries:

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "proposals"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
