collections:
  projects:
    output: true
    permalink: /:collection/:name
    order:
      - 2021-virtual-tour.md
      - 2019-wedding.md
      - IntSoc.md
      - Bla-Bla-language-Cafe.md
      - Glastonbury_Close_Circle_Proposal.md
      - 16th_Bday_Party_Proposal.md
  testimonials:
  jobs:

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
