collections:
  projects:
    output: true
    permalink: /:collection/:name
    sort_by: sort
  testimonials:
  jobs:

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
